# Generated by Django 2.2.3 on 2019-11-06 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pric', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='product/static/IMG')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
