# Generated by Django 2.2.3 on 2019-11-06 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.MemberType')),
            ],
        ),
    ]
