# Generated by Django 2.2.3 on 2019-11-06 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderM',
            fields=[
                ('orderID', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('samt', models.IntegerField()),
                ('sqty', models.IntegerField()),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='OrderD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amt', models.IntegerField()),
                ('orderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.OrderM')),
                ('productID', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
