# Generated by Django 2.2.3 on 2019-11-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderd',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderM'),
        ),
        migrations.RemoveField(
            model_name='orderd',
            name='productID',
        ),
        migrations.AddField(
            model_name='orderd',
            name='productID',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
    ]
