# Generated by Django 2.2.3 on 2019-11-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191106_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderd',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
